"""add owner_id

Revision ID: 6fb65c1c54ee
Revises: 04e4874eb02b
Create Date: 2024-03-04 11:07:25.141358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb65c1c54ee'
down_revision: Union[str, None] = '04e4874eb02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'owner_id')
    # ### end Alembic commands ###
