"""added team table

Revision ID: 4cc2a80bb338
Revises: 3848f9165405
Create Date: 2024-02-02 14:02:36.374035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc2a80bb338'
down_revision: Union[str, None] = '3848f9165405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('INITIATION', 'PLANNING', 'DESIGN', 'DEVELOPMENT', 'TESTING', 'READY', name='statuschoices'), server_default='Initiation', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_title'), 'teams', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_title'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
